name: Build and deploy Vite app to Azure Web App - pramodlohra

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and build Vite app
        run: |
          npm install
          npm run build

      - name: Zip dist folder for deployment
        run: |
          cd dist
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: vite-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: vite-app

      - name: Unzip artifact
        run: unzip release.zip -d site

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_339EAB27D36A4C87A9F980D281AA9AB3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3773D59DCA9A4A4E8FE02576DDCA6F19 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B3EC7FE1AEE9425EB68DCA713F414BE0 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pramodlohra'
          slot-name: 'Production'
          package: site
